"""
Django settings for LoanMS project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4pb!m-+7fj-@@ixyu8yw7tjx464nwnys1p(z@=+b4v_(()-0%9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '0.0.0.0']
INTERNAL_IPS = ['127.0.0.1', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'rest_framework',

    # User Generated Apps
   'webpush',
    'home',
    'selfserv',
    'bankmgr',
    'mdmteam',
    'RestWService',
    #'users',
    'UploadCSV',
    'csvfile'
]
AUTH_USER_MODEL = 'selfserv.Login'
WEBPUSH_SETTINGS = {
   "VAPID_PUBLIC_KEY": "BOwIbLLqKYXibmnG2lPxEXhImI_YzxppYBjKGJKLYMFG7iyUD4VxAq6nA5dYCd_2fiztkOKcSBQl6hteWxA7hAQ",
   "VAPID_PRIVATE_KEY": "YtknHZY07vGrBBlcUREsJNqIBzGm-3LCCRDXvcwk-3Y",
   "VAPID_ADMIN_EMAIL": "vpwalake@gmail.com"
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LoanMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/Users/tanvi/LoanMS/home/templates/',

                 '/Users/tanvi/LoanMS/mdmteam/templates/',
                 os.path.join(BASE_DIR, 'templates'),
                 os.path.join(BASE_DIR, 'selfserv', 'templates', ),
                 os.path.join(BASE_DIR, 'RestWService', 'templates',os.path.join(BASE_DIR, 'selfserv', 'selfserv', ), )],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
STATICFILES_DIRS=[os.path.join(BASE_DIR, 'static')]

WSGI_APPLICATION = 'LoanMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql'
        , 'NAME': 'loan'
        , 'USER': 'root'
        , 'PASSWORD': '123456'
        , 'HOST': '127.0.0.1'
        , 'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
#LOGIN_REDIRECT_URL = 'http://127.0.0.1:8002'
LOGIN_REDIRECT_URL = 'home'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
